"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Basic translations - in a real app, this would be much more comprehensive
const translations = {
  ar: {
    // Dashboard
    dashboard: "لوحة التحكم",
    overview: "نظرة عامة",
    queues: "إدارة الطوابير",
    analytics: "الإحصائيات",
    qrCodes: "رموز QR",
    staff: "الموظفين",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    welcome: "مرحباً",
    totalTickets: "إجمالي التذاكر",
    waiting: "في الانتظار",
    completed: "مكتملة",
    avgWaitTime: "متوسط وقت الانتظار",
    completionRate: "معدل الإنجاز",
    today: "اليوم",
    minutes: "دقيقة",
    percent: "٪",
    noData: "لا توجد بيانات",
    loading: "جاري التحميل...",
    error: "خطأ",
    success: "نجح",
    dashboardOverviewHeader: "نظرة عامة",
    dashboardOverviewSubheading: "مرحباً بك مجدداً، إليك ملخص نشاط محلك اليوم",
    activeQueues: "الطوابير النشطة",
    viewAll: "عرض الكل",
    open: "مفتوح",
    paused: "متوقف",
    peopleWaiting: "أشخاص في الانتظار",
    perCustomer: "د للعميل",
    needHelp: "تحتاج مساعدة؟",
    helpText: "تواصل مع الدعم الفني أو اطلع على دليل الاستخدام لتحقيق أقصى استفادة.",
    helpGuide: "دليل الاستخدام",
    latestMembers: "آخر المنضمين",
    newCustomer: "عميل جديد #",
    minutesAgo: "قبل",
    analyticsLoading: "جاري تحميل الإحصائيات...",
    analyticsNoShop: "تأكد من وجود محل مرتبط بحسابك",
    completedToday: "مكتملة اليوم",
    avgWait: "متوسط وقت الانتظار",
    weeklyStats: "الإحصائيات الأسبوعية",
    hourlyDistribution: "توزيع التذاكر بالساعة (اليوم)",
    queuePerformance: "أداء الطوابير",
    avgService: "متوسط الخدمة",
    queueInQueue: "في الانتظار",
    pauseQueue: "إيقاف مؤقت",
    resumeQueue: "تفعيل",
    analyticsLoadError: "فشل في تحميل الإحصائيات",
    manage: "إدارة",
    active: "نشط",
    or: "أو",
    minutesAgoSuffix: "دقائق",
    // Common
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    add: "إضافة",
    search: "بحث",
    filter: "تصفية",
    status: "الحالة",
    actions: "الإجراءات",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    address: "العنوان",
    date: "التاريخ",
    time: "الوقت",
    general: "عام",
    notifications: "الإشعارات",
    appearance: "المظهر",
    subscription: "الاشتراك",
    security: "الأمان",
    workingHours: "أوقات العمل",
    registrationControl: "التحكم في التسجيل",
    manageSettings: "إدارة إعدادات المحل",
    language: "اللغة",
    arabic: "العربية",
    theme: "السمة",
    light: "وضع النهار",
    dark: "وضع الليل",
    system: "النظام",
    languageNote: "اختر اللغة المفضلة لتغيير اتجاه التطبيق والمحتوى.",
    saveSettings: "حفظ التغييرات",
    openTime: "وقت فتح المحل",
    closeTime: "وقت إغلاق المحل",
    regStartTime: "وقت بدء التسجيل",
    regEndTime: "وقت إغلاق التسجيل",
    dailyLimit: "الحد اليومي للعملاء",
    autoReset: "تصفير الطوابير تلقائياً",
    workingDays: "أيام العمل",
    breakTimes: "أوقات الاستراحة",
    addBreak: "إضافة استراحة",
    breakTitle: "عنوان الاستراحة",
    startTime: "وقت البدء",
    endTime: "وقت الانتهاء",
    isActive: "نشط",
    shopStatus: "حالة المحل",
    shopOpen: "مفتوح",
    shopClosed: "مغلق",
    shopBreak: "استراحة",
    limitReached: "تم اكتمال العدد اليومي",
    registrationClosed: "التسجيل مغلق",
    retry: "إعادة المحاولة",
    successUpdate: "تم تحديث الإعدادات بنجاح",
    errorUpdate: "فشل تحديث الإعدادات",
    shopLogo: "شعار المحل",
    logoHint: "يفضل أن يكون الشعار بصيغة مربعة 1:1",
    shopNameAr: "اسم المحل (بالعربية)",
    shopNameEn: "اسم المحل (بالانجليزية)",
    notificationsCustomer: "إشعارات العملاء",
    notificationsStaff: "إشعارات الموظفين",
    smsNotifications: "رسائل SMS",
    currentPlan: "الخطة الحالية",
    freePlan: "مجانية",
    planExpires: "تجربة لمدة 7 أيام",
    planFeatures: ["طابور واحد", "موظفان", "إحصائيات يومية", "QR قياسي"],
    upgradePlan: "ترقية الاشتراك",
    promoCode: "كود الخصم",
    processing: "جاري المعالجة...",
    upgradeSuccess: "تم ترقية الاشتراك",
    dangerZone: "منطقة الخطر",
    deleteShopWarning: "حذف المحل سيؤدي لإزالة كافة البيانات والطوابير والإحصائيات بشكل نهائي. لا يمكن التراجع عن هذا الإجراء.",
    ownerRole: "صاحب المحل",
    // Landing page
    login: "تسجيل الدخول",
    register: "ابدأ مجاناً",
    tagline: "منصة إدارة الطوابير الأولى في السوق العربي",
    heroTitle1: "وداعاً",
    heroTitle2: "للانتظار الطويل",
    heroDescription: "منصة ذكية تتيح لعملائك الانضمام للطابور بمسح QR واحد، ومتابعة دورهم من أي مكان — بدون تطبيق.",
    startFreeTrialCta: "ابدأ تجربتك المجانية",
    dashboardLoginCta: "دخول لوحة التحكم",
    trustBadges: ["لا يحتاج تطبيق", "مجاني للبدء", "إعداد في 5 دقائق", "دعم عربي كامل"],
    shopsStats: "10,000+",
    shopsStatsLabel: "عميل يومياً",
    businessStats: "500+",
    businessStatsLabel: "محل مشترك",
    satisfactionStats: "98%",
    satisfactionStatsLabel: "رضا العملاء",
    joinSpeedStats: "< 3ث",
    joinSpeedStatsLabel: "سرعة الانضمام",
    shopTypesTitle: "يناسب كل أنواع المحلات",
    shopTypesSubtitle: "مصمم خصيصاً للمحلات الخدمية في السوق العربي",
    barbershops: "صالونات الحلاقة",
    restaurants: "المطاعم",
    clinics: "العيادات",
    carWashes: "مغاسل السيارات",
    beautySalons: "صالونات التجميل",
    featuresTitle: "كل ما تحتاجه في مكان واحد",
    featuresSubtitle: "ميزات قوية لتحويل تجربة الانتظار في محلك",
    featureQr: "مسح QR فوري",
    featureQrDesc: "العميل يمسح الكود ويحصل على رقمه مباشرة بدون تحميل أي تطبيق",
    featureWaitTime: "وقت انتظار دقيق",
    featureWaitTimeDesc: "احسب الوقت المتوقع لدورك بدقة عالية بناءً على متوسط الخدمة",
    featureNotifications: "إشعارات لحظية",
    featureNotificationsDesc: "إشعار فوري عند اقتراب دورك حتى لا تفوتك لحظة",
    featureAnalytics: "إحصائيات متقدمة",
    featureAnalyticsDesc: "لوحة تحكم احترافية مع تقارير يومية وأوقات الذروة",
    featureSecurity: "آمن ومحمي",
    featureSecurityDesc: "أمان على مستوى المؤسسات مع تشفير كامل وحماية البيانات",
    featureSpeed: "سريع للغاية",
    featureSpeedDesc: "منصة مُحسَّنة للسرعة القصوى مع تحديثات فورية",
    howItWorksTitle: "كيف يعمل دورك؟",
    howItWorksSubtitle: "من تجربة العميل إلى لوحة التحكم، كل خطوة محسوبة بعناية",
    howStepScan: "امسح الكود",
    howStepScanDesc: "العميل يمسح QR وينضم للطابور في ثانية واحدة",
    howStepWait: "تابع الوقت",
    howStepWaitDesc: "يعرف العميل موقعه والتوقعات دون الانتظار في الصف",
    howStepServe: "يُستدعى مباشرة",
    howStepServeDesc: "تنبيه لحظي عند اقتراب دوره، لتجربة أسرع وأكثر سلاسة",
    queueFlowTitle: "تدفق الطابور بلمحة واحدة",
    queueFlowSubtitle: "رؤية واضحة لكل خطوة من انضمام العميل حتى الخدمة",
    dashboardPreviewTitle: "لوحة تحكم احترافية",
    dashboardPreviewSubtitle: "إحصائيات وبيانات تساعدك في اتخاذ قرار سريع",
    benefitsTitle: "لماذا يختارك عملاؤك؟",
    benefitsSubtitle: "قيمة واضحة ونتائج سريعة لكل متجر",
    benefitBuiltFor: "مصممة للسوق العربي",
    benefitNoApp: "لا حاجة لتحميل تطبيق",
    benefitSaveTime: "توفير وقت واستجابة أسرع",
    benefitSupport: "دعم مباشر وسريع",
    statsTitle: "نتائج ملموسة",
    statsSubtitle: "أرقام تعكس قوة النظام وسهولة اعتماده",
    testimonialsTitle: "آراء العملاء",
    testimonialsSubtitle: "تجارب حقيقية من محلات اعتمدت دورك",
    testimonialQuote1: "دورك غيّر تجربة عملائنا بالكامل، أصبحنا أكثر تنظيماً وسرعة.",
    testimonialAuthor1: "فاطمة من صالون نور",
    testimonialRole1: "مديرة الصالون",
    testimonialQuote2: "العملاء أصبحوا يأتون في الوقت المناسب، والإشعارات حسنت تجربتهم كثيراً.",
    testimonialAuthor2: "سعود من مطعم ليمون",
    testimonialRole2: "مالك المطعم",
    testimonialQuote3: "منصة سلسة وسهلة، وتم تفعيلها بسرعة بدون أي تعقيد.",
    testimonialAuthor3: "هدى من عيادة سما",
    testimonialRole3: "مستشارة إدارة",
    pricingTitle: "خطط أسعار شفافة",
    pricingSubtitle: "خطط تبدأ مجاناً وتنمو مع عملك",
    faqTitle: "الأسئلة الأكثر شيوعاً",
    faqSubtitle: "إجابات سريعة لتبدأ بثقة",
    faqQuestion1: "هل يحتاج العملاء لتحميل تطبيق؟",
    faqAnswer1: "لا، العميل يدخل عبر مسح QR فقط ويتابع دوره من المتصفح.",
    faqQuestion2: "كيف أبدأ في دورك؟",
    faqAnswer2: "سجل مجاناً، أضف متجرك، واطبع رمز QR للمكان — وستكون جاهزاً في دقائق.",
    faqQuestion3: "هل يدعم دورك أكثر من موظف؟",
    faqAnswer3: "نعم، يمكنك إدارة طوابير متعددة وفريق عمل كامل بسهولة.",
    faqQuestion4: "هل يصلح لجميع المحلات الخدمية؟",
    faqAnswer4: "نعم، صُمم دورك لصالونات الحلاقة والمطاعم والعيادات والمزيد.",
    footerTitle: "ابدأ إدارة طوابيرك بشكل احترافي",
    footerAbout: "منصة دورك تساعدك في تحويل تجربة العملاء إلى أسرع وأكثر حداثة.",
    footerLinks: ["الميزات", "كيف يعمل", "الخطط", "الأسئلة"],
    footerContact: "تواصل معنا لأي استفسار أو دعم",
    footerSocial: "تابعنا على وسائل التواصل",
    ctaTitle: "ابدأ اليوم — مجاناً",
    ctaDescription: "أنشئ حسابك وابدأ في إدارة طابورك الأول خلال 5 دقائق",
    ctaButton: "ابدأ مجاناً الآن",
  },
  en: {
    // Dashboard
    dashboard: "Dashboard",
    overview: "Overview",
    queues: "Queues",
    analytics: "Analytics",
    qrCodes: "QR Codes",
    staff: "Staff",
    settings: "Settings",
    logout: "Logout",
    welcome: "Welcome",
    totalTickets: "Total Tickets",
    waiting: "Waiting",
    completed: "Completed",
    avgWaitTime: "Avg Wait Time",
    completionRate: "Completion Rate",
    today: "Today",
    minutes: "min",
    percent: "%",
    noData: "No Data",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    dashboardOverviewHeader: "Overview",
    dashboardOverviewSubheading: "Welcome back, here's a summary of today's activity",
    activeQueues: "Active Queues",
    viewAll: "View All",
    open: "Open",
    paused: "Paused",
    peopleWaiting: "people waiting",
    perCustomer: "min/customer",
    needHelp: "Need Help?",
    helpText: "Contact support or read the guide to get the most out of the system.",
    helpGuide: "Usage Guide",
    latestMembers: "Latest Joiners",
    newCustomer: "New Customer #",
    minutesAgo: "min ago",
    analyticsLoading: "Loading analytics...",
    analyticsNoShop: "Ensure a shop is linked to your account",
    completedToday: "Completed Today",
    avgWait: "Avg Wait",
    weeklyStats: "Weekly Stats",
    hourlyDistribution: "Hourly Distribution (Today)",
    queuePerformance: "Queue Performance",
    avgService: "Avg Service",
    queueInQueue: "In Queue",
    pauseQueue: "Pause",
    resumeQueue: "Resume",
    analyticsLoadError: "Failed to load analytics",
    manage: "Manage",
    active: "Active",
    or: "or",
    minutesAgoSuffix: "min ago",
    // Common
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    search: "Search",
    filter: "Filter",
    status: "Status",
    actions: "Actions",
    name: "Name",
    email: "Email",
    phone: "Phone",
    address: "Address",
    date: "Date",
    time: "Time",
    general: "General",
    notifications: "Notifications",
    appearance: "Appearance",
    subscription: "Subscription",
    security: "Security",
    workingHours: "Working Hours",
    registrationControl: "Registration Control",
    manageSettings: "Manage Shop Settings",
    language: "Language",
    arabic: "Arabic",
    theme: "Theme",
    light: "Light Mode",
    dark: "Dark Mode",
    system: "System",
    languageNote: "Choose your preferred language to change app direction and content.",
    saveSettings: "Save Changes",
    openTime: "Open Time",
    closeTime: "Close Time",
    regStartTime: "Reg Start Time",
    regEndTime: "Reg End Time",
    dailyLimit: "Daily Limit",
    autoReset: "Auto Reset Daily",
    workingDays: "Working Days",
    breakTimes: "Break Times",
    addBreak: "Add Break",
    breakTitle: "Break Title",
    startTime: "Start Time",
    endTime: "End Time",
    isActive: "Active",
    shopStatus: "Shop Status",
    shopOpen: "Open",
    shopClosed: "Closed",
    shopBreak: "Break",
    limitReached: "Daily Limit Reached",
    registrationClosed: "Registration Closed",
    retry: "Retry",
    successUpdate: "Settings updated successfully",
    errorUpdate: "Failed to update settings",
    shopLogo: "Shop Logo",
    logoHint: "1:1 ratio logo is recommended",
    shopNameAr: "Shop Name (Arabic)",
    shopNameEn: "Shop Name (English)",
    notificationsCustomer: "Customer Notifications",
    notificationsStaff: "Staff Notifications",
    smsNotifications: "SMS Notifications",
    currentPlan: "Current Plan",
    freePlan: "Free",
    planExpires: "7 days trial",
    planFeatures: ["One queue", "Two staff", "Daily analytics", "Standard QR"],
    upgradePlan: "Upgrade Subscription",
    promoCode: "Promo code",
    processing: "Processing...",
    upgradeSuccess: "Subscription upgraded",
    dangerZone: "Danger Zone",
    deleteShopWarning: "Deleting the shop will remove all data, queues, and analytics permanently. This action cannot be undone.",
    ownerRole: "Shop Owner",
    // Landing page
    login: "Login",
    register: "Get Started",
    tagline: "The first queue management platform in the Arab market",
    heroTitle1: "Say goodbye to",
    heroTitle2: "long wait times",
    heroDescription: "A smart platform that lets your customers join the queue with a single QR scan and track their turn from anywhere — no app required.",
    startFreeTrialCta: "Start free trial",
    dashboardLoginCta: "Dashboard login",
    trustBadges: ["No app needed", "Free to start", "Setup in 5 minutes", "Full Arabic support"],
    shopsStats: "10,000+",
    shopsStatsLabel: "customers daily",
    businessStats: "500+",
    businessStatsLabel: "businesses",
    satisfactionStats: "98%",
    satisfactionStatsLabel: "customer satisfaction",
    joinSpeedStats: "< 3s",
    joinSpeedStatsLabel: "join speed",
    shopTypesTitle: "Suitable for all types of shops",
    shopTypesSubtitle: "Designed specifically for service businesses in the Arab market",
    barbershops: "Barbershops",
    restaurants: "Restaurants",
    clinics: "Clinics",
    carWashes: "Car washes",
    beautySalons: "Beauty salons",
    featuresTitle: "Everything you need in one place",
    featuresSubtitle: "Powerful features to transform the waiting experience at your shop",
    featureQr: "Instant QR scan",
    featureQrDesc: "Customer scans the code and gets their number immediately without downloading any app",
    featureWaitTime: "Accurate wait time",
    featureWaitTimeDesc: "Calculate the expected waiting time with high accuracy based on average service time",
    featureNotifications: "Instant notifications",
    featureNotificationsDesc: "Get notified instantly when it's your turn so you don't miss a moment",
    featureAnalytics: "Advanced analytics",
    featureAnalyticsDesc: "Professional dashboard with daily reports and peak time analysis",
    featureSecurity: "Secure & protected",
    featureSecurityDesc: "Enterprise-level security with full encryption and data protection",
    featureSpeed: "Ultra-fast",
    featureSpeedDesc: "Platform optimized for maximum speed with instant updates",
    howItWorksTitle: "How it works",
    howItWorksSubtitle: "From customer arrival to the dashboard, every step is designed to reduce waiting time",
    howStepScan: "Scan QR",
    howStepScanDesc: "Customers join the queue in one scan and skip the line",
    howStepWait: "Track wait time",
    howStepWaitDesc: "See position, estimated time and progress in real time",
    howStepServe: "Get notified",
    howStepServeDesc: "Receive instant alerts when the customer’s turn is ready",
    queueFlowTitle: "Queue flow at a glance",
    queueFlowSubtitle: "A crisp visual journey from arrival to service",
    dashboardPreviewTitle: "Professional dashboard",
    dashboardPreviewSubtitle: "Insights and controls that help your team act faster",
    benefitsTitle: "Why customers choose you",
    benefitsSubtitle: "Clear value and faster results for your business",
    benefitBuiltFor: "Built for the Arab market",
    benefitNoApp: "No app required",
    benefitSaveTime: "Save time and speed up service",
    benefitSupport: "Fast support and setup",
    statsTitle: "Real results",
    statsSubtitle: "Numbers that show how the platform boosts operations",
    testimonialsTitle: "Customer stories",
    testimonialsSubtitle: "Real businesses that transformed their wait experience",
    testimonialQuote1: "Dorak changed our customer flow completely and made service much faster.",
    testimonialAuthor1: "Fatima from Noor Salon",
    testimonialRole1: "Salon Manager",
    testimonialQuote2: "Customers now arrive at the right time, and alerts improved the experience significantly.",
    testimonialAuthor2: "Saud from Lemon Restaurant",
    testimonialRole2: "Owner",
    testimonialQuote3: "A smooth platform with fast onboarding, no complexity at all.",
    testimonialAuthor3: "Huda from Sama Clinic",
    testimonialRole3: "Operations Advisor",
    pricingTitle: "Transparent pricing",
    pricingSubtitle: "Plans that start free and grow with your business",
    faqTitle: "Frequently asked questions",
    faqSubtitle: "Quick answers to help you start confidently",
    faqQuestion1: "Do customers need an app?",
    faqAnswer1: "No. Customers join the queue with a QR scan and follow their turn in the browser.",
    faqQuestion2: "How do I start with Dorak?",
    faqAnswer2: "Sign up for free, add your shop, print the QR code, and you are ready in minutes.",
    faqQuestion3: "Can Dorak support multiple staff?",
    faqAnswer3: "Yes, you can manage multiple queues and a full team easily.",
    faqQuestion4: "Is it suitable for service businesses?",
    faqAnswer4: "Yes, Dorak is built for barbershops, restaurants, clinics, and more.",
    footerTitle: "Manage queues with confidence",
    footerAbout: "Dorak helps you turn customer waiting into a fast, modern experience.",
    footerLinks: ["Features", "How it works", "Pricing", "FAQ"],
    footerContact: "Contact us for questions or support",
    footerSocial: "Follow us on social media",
    ctaTitle: "Start today — for free",
    ctaDescription: "Create your account and start managing your first queue in 5 minutes",
    ctaButton: "Start for free now",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ar');

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem('dorak-language') as Language;
    if (savedLanguage && (savedLanguage === 'ar' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('dorak-language', lang);
  };

  const isRTL = language === 'ar';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
  }, [language, isRTL]);

  const t = (key: string): string => {
    const value = translations[language][key as keyof typeof translations.ar];
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}