-- AlterTable
ALTER TABLE `subscriptions` ADD COLUMN `activatedByAdmin` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isTrial` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'INACTIVE';

-- AlterTable
ALTER TABLE `users` ADD COLUMN `accountStatus` ENUM('ACTIVE', 'PENDING', 'SUSPENDED', 'DEACTIVATED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `approvedAt` DATETIME(3) NULL,
    ADD COLUMN `approvedBy` VARCHAR(191) NULL,
    ADD COLUMN `isApproved` BOOLEAN NOT NULL DEFAULT false;
